-- Milestone 3E: API-managed rich menu definitions and safe assignments.
create table public.rich_menus (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null check (char_length(btrim(name)) between 1 and 150), line_rich_menu_id text, rich_menu_alias_id text, chat_bar_text text, width integer, height integer, selected boolean not null default false, image_asset_id uuid references public.media_assets(id) on delete set null, definition_json jsonb not null default '{}'::jsonb, status text not null default 'draft' check (status in ('draft','active','paused','deleted')), is_default boolean not null default false, managed_by text not null default 'api' check (managed_by in ('api','external')), created_by_profile_id uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, name)
);
create index rich_menus_default_idx on public.rich_menus (organization_id, is_default) where status <> 'deleted';
create table public.rich_menu_areas (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, rich_menu_id uuid not null, area_order integer not null check (area_order >= 0), x integer not null check (x >= 0), y integer not null check (y >= 0), width integer not null check (width > 0), height integer not null check (height > 0), action_type text not null check (action_type in ('uri','message','postback')), action_config_json jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, rich_menu_id, area_order), foreign key (organization_id, rich_menu_id) references public.rich_menus(organization_id, id) on delete cascade
);
create table public.rich_menu_rules (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, rich_menu_id uuid not null, priority integer not null default 0, conditions_json jsonb not null default '{}'::jsonb, is_active boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key (organization_id, rich_menu_id) references public.rich_menus(organization_id, id) on delete cascade
);
create table public.rich_menu_assignments (
  organization_id uuid not null references public.organizations(id) on delete cascade, contact_id uuid not null, rich_menu_id uuid not null, source_type text not null, source_id text, status text not null default 'pending' check (status in ('pending','synced','failed','removed')), line_synced_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key (organization_id, contact_id), foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on delete cascade, foreign key (organization_id, rich_menu_id) references public.rich_menus(organization_id, id) on delete cascade
);
do $$ declare table_name text; begin foreach table_name in array array['rich_menus','rich_menu_areas','rich_menu_rules','rich_menu_assignments'] loop execute format('alter table public.%I enable row level security', table_name); execute format('create policy %I_select_member on public.%I for select to authenticated using (public.is_organization_member(organization_id))', table_name, table_name); execute format('create policy %I_manage_admin on public.%I for all to authenticated using (public.is_organization_admin(organization_id)) with check (public.is_organization_admin(organization_id))', table_name, table_name); end loop; end $$;
