-- Milestone 3F: attribution, safe tracked links, behavior events and rollups.
create table public.attribution_sources (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null check (char_length(btrim(name)) between 1 and 150), slug text not null check (slug ~ '^[a-z0-9-]{1,100}$'), channel text not null, campaign text, content text, destination_type text not null default 'url', destination_value text not null, is_active boolean not null default true, created_by_profile_id uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, slug)
);
create table public.tracked_links (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null, slug text not null check (slug ~ '^[a-z0-9-]{1,100}$'), destination_url text not null, source_id uuid references public.attribution_sources(id) on delete set null, is_personalized boolean not null default false, is_active boolean not null default true, created_by_profile_id uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, slug)
);
create table public.link_clicks (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, tracked_link_id uuid not null, contact_id uuid, source_id uuid, attribution_type text not null check (attribution_type in ('deterministic','estimated')), clicked_at timestamptz not null default now(), ip_hash text, user_agent_hash text, metadata_json jsonb not null default '{}', foreign key (organization_id, tracked_link_id) references public.tracked_links(organization_id, id) on delete cascade, foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on delete set null
);
create index link_clicks_reporting_idx on public.link_clicks (organization_id, tracked_link_id, clicked_at desc);
create table public.contact_attributions (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, contact_id uuid not null, source_id uuid not null, attribution_type text not null check (attribution_type in ('deterministic','estimated')), is_first_touch boolean not null default false, is_last_touch boolean not null default false, attributed_at timestamptz not null default now(), created_at timestamptz not null default now(), foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on delete cascade, foreign key (organization_id, source_id) references public.attribution_sources(organization_id, id) on delete cascade
);
create table public.behavior_events (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, contact_id uuid, event_type text not null, event_key text not null, resource_type text, resource_id uuid, occurred_at timestamptz not null default now(), metadata_json jsonb not null default '{}', foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on delete set null
);
create index behavior_events_reporting_idx on public.behavior_events (organization_id, event_type, occurred_at desc);
create table public.conversions (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, contact_id uuid, conversion_type text not null, conversion_key text not null, value_amount numeric, currency text, source_id uuid, occurred_at timestamptz not null default now(), metadata_json jsonb not null default '{}', foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on delete set null, foreign key (organization_id, source_id) references public.attribution_sources(organization_id, id) on delete set null
);
create table public.daily_metric_snapshots (
  organization_id uuid not null references public.organizations(id) on delete cascade, metric_date date not null, metric_key text not null, dimension_type text not null default '', dimension_id uuid not null default '00000000-0000-0000-0000-000000000000', value_number numeric not null default 0, metadata_json jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key (organization_id, metric_date, metric_key, dimension_type, dimension_id)
);
create table public.funnel_definitions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null, description text not null default '', is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, name));
create table public.funnel_steps (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, funnel_id uuid not null, step_order integer not null, name text not null, event_type text not null, conditions_json jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, funnel_id, step_order), foreign key (organization_id, funnel_id) references public.funnel_definitions(organization_id, id) on delete cascade);
do $$ declare table_name text; begin foreach table_name in array array['attribution_sources','tracked_links','link_clicks','contact_attributions','behavior_events','conversions','daily_metric_snapshots','funnel_definitions','funnel_steps'] loop execute format('alter table public.%I enable row level security', table_name); execute format('create policy %I_select_member on public.%I for select to authenticated using (public.is_organization_member(organization_id))', table_name, table_name); execute format('create policy %I_manage_admin on public.%I for all to authenticated using (public.is_organization_admin(organization_id)) with check (public.is_organization_admin(organization_id))', table_name, table_name); end loop; end $$;
