-- Milestone 3D: LINE chat surveys and idempotent answer actions.
create table public.surveys (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null check (char_length(btrim(name)) between 1 and 150), description text not null default '', status text not null default 'draft' check (status in ('draft','active','paused','completed')), starts_at timestamptz, ends_at timestamptz, allow_multiple_responses boolean not null default false, allow_answer_changes boolean not null default false, completion_template_id uuid, settings_json jsonb not null default '{}'::jsonb, created_by_profile_id uuid references public.profiles(id) on delete set null, approved_by_profile_id uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, name)
);
create table public.survey_questions (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, survey_id uuid not null, question_key text not null check (question_key ~ '^[a-z][a-z0-9_]{0,63}$'), title text not null check (char_length(title) between 1 and 500), description text not null default '', question_type text not null check (question_type in ('single_choice','multiple_choice','free_text','number','date','confirm')), is_required boolean not null default true, sort_order integer not null default 0, settings_json jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, survey_id, question_key), foreign key (organization_id, survey_id) references public.surveys(organization_id, id) on delete cascade
);
create table public.survey_options (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, question_id uuid not null, option_key text not null, label text not null check (char_length(label) between 1 and 100), value text not null, sort_order integer not null default 0, postback_token text not null, action_config_json jsonb not null default '{}'::jsonb, next_question_id uuid, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, question_id, option_key), unique (organization_id, postback_token), foreign key (organization_id, question_id) references public.survey_questions(organization_id, id) on delete cascade
);
create table public.survey_sessions (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, survey_id uuid not null, contact_id uuid not null, status text not null default 'active' check (status in ('active','waiting_text','completed','expired','cancelled')), current_question_id uuid, started_at timestamptz not null default now(), completed_at timestamptz, expires_at timestamptz not null, last_interaction_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key (organization_id, survey_id) references public.surveys(organization_id, id) on delete cascade, foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on delete cascade
);
create index survey_sessions_active_contact_idx on public.survey_sessions (organization_id, contact_id, status, expires_at);
create table public.survey_responses (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, survey_id uuid not null, question_id uuid not null, option_id uuid, contact_id uuid not null, session_id uuid not null, answer_text text, answer_number numeric, answer_date date, answer_json jsonb, response_version integer not null default 1, webhook_event_id text, answered_at timestamptz not null default now(), created_at timestamptz not null default now(), foreign key (organization_id, survey_id) references public.surveys(organization_id, id) on delete cascade, foreign key (organization_id, question_id) references public.survey_questions(organization_id, id) on delete cascade, foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on delete cascade, foreign key (organization_id, session_id) references public.survey_sessions(organization_id, id) on delete cascade
);
create index survey_responses_analytics_idx on public.survey_responses (organization_id, survey_id, question_id, answered_at);
create table public.survey_action_executions (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, survey_response_id uuid not null, action_type text not null, idempotency_key text not null, status text not null default 'pending' check (status in ('pending','succeeded','failed')), error_message_safe text, executed_at timestamptz, created_at timestamptz not null default now(), unique (organization_id, idempotency_key), foreign key (organization_id, survey_response_id) references public.survey_responses(organization_id, id) on delete cascade
);
do $$ declare table_name text; begin foreach table_name in array array['surveys','survey_questions','survey_options','survey_sessions','survey_responses','survey_action_executions'] loop execute format('alter table public.%I enable row level security', table_name); execute format('create policy %I_select_member on public.%I for select to authenticated using (public.is_organization_member(organization_id))', table_name, table_name); execute format('create policy %I_manage_admin on public.%I for all to authenticated using (public.is_organization_admin(organization_id)) with check (public.is_organization_admin(organization_id))', table_name, table_name); end loop; end $$;
