-- Milestone 3C: versioned scenarios and keyword rules.
create table public.automation_scenarios (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 150), description text not null default '', trigger_type text not null check (trigger_type in ('follow','tag_added','tag_removed','survey_answered','survey_completed','custom_field_changed','tracked_link_clicked','manual')),
  trigger_config_json jsonb not null default '{}'::jsonb, status text not null default 'draft' check (status in ('draft','active','paused')), allow_reentry boolean not null default false, reentry_cooldown_seconds integer not null default 0 check (reentry_cooldown_seconds >= 0), version integer not null default 1 check (version > 0),
  created_by_profile_id uuid references public.profiles(id) on delete set null, approved_by_profile_id uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, name, version)
);
create table public.automation_steps (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, scenario_id uuid not null, step_order integer not null check (step_order >= 0), step_type text not null check (step_type in ('send_message','wait_duration','wait_until','add_tag','remove_tag','set_custom_field','branch','start_scenario','stop_scenario','end')), config_json jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, scenario_id, step_order), foreign key (organization_id, scenario_id) references public.automation_scenarios(organization_id, id) on delete cascade
);
create table public.automation_enrollments (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, scenario_id uuid not null, scenario_version integer not null, contact_id uuid not null, status text not null default 'active' check (status in ('active','waiting','completed','stopped','failed')), current_step_order integer not null default 0, next_execution_at timestamptz, idempotency_key text not null, started_at timestamptz not null default now(), completed_at timestamptz, stopped_at timestamptz, last_error_safe text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, idempotency_key), foreign key (organization_id, scenario_id) references public.automation_scenarios(organization_id, id) on delete cascade, foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on delete cascade
);
create index automation_enrollments_due_idx on public.automation_enrollments (organization_id, status, next_execution_at);
create table public.auto_reply_rules (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null check (char_length(btrim(name)) between 1 and 150), match_type text not null check (match_type in ('exact','prefix','contains','regex')), pattern text not null check (char_length(pattern) between 1 and 200), normalized_pattern text not null, priority integer not null default 0, conditions_json jsonb not null default '{}'::jsonb, active_from timestamptz, active_until timestamptz, day_time_config_json jsonb not null default '{}'::jsonb, action_config_json jsonb not null default '{}'::jsonb, stop_after_match boolean not null default true, is_active boolean not null default false, created_by_profile_id uuid references public.profiles(id) on delete set null, approved_by_profile_id uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index auto_reply_rules_priority_idx on public.auto_reply_rules (organization_id, is_active, priority desc);
do $$ declare table_name text; begin foreach table_name in array array['automation_scenarios','automation_steps','automation_enrollments','auto_reply_rules'] loop execute format('alter table public.%I enable row level security', table_name); execute format('create policy %I_select_member on public.%I for select to authenticated using (public.is_organization_member(organization_id))', table_name, table_name); execute format('create policy %I_manage_admin on public.%I for all to authenticated using (public.is_organization_admin(organization_id)) with check (public.is_organization_admin(organization_id))', table_name, table_name); end loop; end $$;
