import "server-only";

import { randomUUID } from "node:crypto";
import { getServerEnv } from "@/lib/env/server";
import { assertLaunchAction, assertTestRecipient } from "@/lib/launch/flags";
import { createLineMulticastClient } from "@/lib/line/send";
import { mediaMessageFromAsset, outboundMessageListSchema, validateMediaUpload, type MediaAsset, type MediaType } from "@/lib/line/media";
import { chunk, dedupeAndExclude, quotaAllows } from "@/lib/milestone3/delivery";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

export type DeliveryTemplate = { id: string; name: string; items: Array<Record<string, unknown>>; isActive: boolean; createdAt: string };
export type DeliveryCampaign = { id: string; name: string; status: string; scheduledAt: string | null; recipientCount: number; excludedCount: number; acceptedCount: number; failedCount: number; batchCount: number; templateId: string | null };
export type DeliveryMedia = MediaAsset & { name: string; status: "ready" | "deleted"; createdAt: string };
const templates: DeliveryTemplate[] = []; const campaigns: Array<DeliveryCampaign & { batches: Array<{ id: string; status: string; retryKey: string; recipientCount: number }> }> = []; const media: DeliveryMedia[] = [];

export function listMockMedia(): DeliveryMedia[] { return media.filter((item) => item.status !== "deleted"); }
export async function createMedia(input: { name: string; type: MediaType; mimeType: string; sizeBytes: number; hasPreview: boolean; durationMs?: number; bytes?: ArrayBuffer }): Promise<DeliveryMedia> {
  const env = getServerEnv(); validateMediaUpload(input, { image: env.MEDIA_IMAGE_MAX_BYTES, video: env.MEDIA_VIDEO_MAX_BYTES, audio: env.MEDIA_AUDIO_MAX_BYTES }); const id = randomUUID(); const storagePath = `${env.LINE_ORGANIZATION_ID || "mock"}/${id}`;
  if (!env.MOCK_LINE_API) { const client = createSupabaseAdminClient(); if (!client) throw new Error("storage database is not configured"); if (!input.bytes) throw new Error("media bytes are required"); const upload = await client.storage.from(env.LINE_MEDIA_BUCKET).upload(storagePath, input.bytes, { contentType: input.mimeType, upsert: false }); if (upload.error) throw new Error("media upload failed"); await client.from("media_assets").insert({ organization_id: env.LINE_ORGANIZATION_ID, asset_type: input.type, name: input.name, storage_bucket: env.LINE_MEDIA_BUCKET, storage_path: storagePath, public_url: null, mime_type: input.mimeType, size_bytes: input.sizeBytes, duration_ms: input.durationMs || null, status: "ready" }); }
  const item: DeliveryMedia = { id, assetType: input.type, publicUrl: `https://storage.invalid/${storagePath}`, mimeType: input.mimeType, sizeBytes: input.sizeBytes, durationMs: input.durationMs, name: input.name, status: "ready", createdAt: new Date().toISOString() }; media.push(item); return item;
}
export async function deleteMedia(id: string): Promise<void> { const item = media.find((candidate) => candidate.id === id); if (item) item.status = "deleted"; const env = getServerEnv(); if (!env.MOCK_LINE_API) { const client = createSupabaseAdminClient(); if (!client) throw new Error("storage database is not configured"); const references = await client.from("message_template_items").select("id").eq("media_asset_id", id).limit(1); if (references.data?.length) throw new Error("使用中のメディアは削除できません。"); } }
export function listMockTemplates(): DeliveryTemplate[] { return templates.filter((item) => item.isActive); }
export function createMockTemplate(input: { name: string; items: Array<Record<string, unknown>> }): DeliveryTemplate { const items = outboundMessageListSchema.parse(input.items); const template = { id: randomUUID(), name: input.name.trim(), items, isActive: true, createdAt: new Date().toISOString() }; templates.push(template); return template; }
export function createMockCampaign(input: { name: string; templateId?: string | null; recipientIds: string[]; scheduledAt?: string | null }): DeliveryCampaign { const unique = [...new Set(input.recipientIds)]; const selected = unique.map((id) => ({ id, friendStatus: "following", marketingStatus: "eligible" })); const result = dedupeAndExclude(selected, getServerEnv().MAX_CAMPAIGN_RECIPIENTS); const batches = chunk(result.recipients, getServerEnv().MAX_MULTICAST_BATCH_SIZE).map((items) => ({ id: randomUUID(), status: "pending", retryKey: randomUUID(), recipientCount: items.length })); const campaign = { id: randomUUID(), name: input.name.trim(), status: input.scheduledAt ? "scheduled" : "ready", scheduledAt: input.scheduledAt ?? null, recipientCount: result.recipients.length, excludedCount: result.excluded, acceptedCount: 0, failedCount: 0, batchCount: batches.length, templateId: input.templateId ?? null, batches }; campaigns.push(campaign); return campaign; }
export function listMockCampaigns(): DeliveryCampaign[] { return campaigns.map(({ batches: _batches, ...campaign }) => campaign); }
export async function dispatchMockCampaign(id: string): Promise<DeliveryCampaign> { const campaign = campaigns.find((item) => item.id === id); if (!campaign) throw new Error("campaign not found"); if (campaign.status === "completed") return campaign; assertLaunchAction("LINE_BULK_SEND_ENABLED"); const template = templates.find((item) => item.id === campaign.templateId); const messages = template?.items?.length ? outboundMessageListSchema.parse(template.items) : [{ type: "text", text: "Mock campaign" }]; const lineMessages = messages.map((message) => message.type === "text" ? message : message); const client = createLineMulticastClient(); for (const batch of campaign.batches) { if (batch.status === "accepted") continue; if (batch.recipientCount > getServerEnv().MAX_MULTICAST_BATCH_SIZE) throw new Error("batch limit exceeded"); const mockRecipients = Array.from({ length: batch.recipientCount }, (_, index) => `mock-test-${index}`); if (!getServerEnv().MOCK_LINE_API) mockRecipients.forEach(assertTestRecipient); const result = await client.multicast({ lineUserIds: mockRecipients, messages: lineMessages as Array<Record<string, unknown>>, retryKey: batch.retryKey }); if (result.accepted) { batch.status = "accepted"; campaign.acceptedCount += batch.recipientCount; } else { batch.status = result.retryable ? "retry_wait" : "failed"; campaign.failedCount += batch.recipientCount; } } campaign.status = campaign.failedCount ? "partially_failed" : "completed"; return campaign; }
