import "server-only";

import { randomUUID } from "node:crypto";
import { customFieldDefinitionSchema, isSuppressed, tagDefinitionSchema, validateSegmentDsl, type SegmentGroup } from "@/lib/milestone3/foundation";

export type FoundationTagGroup = { id: string; name: string; isExclusive: boolean; isActive: boolean };
export type FoundationTag = FoundationTagGroup & { tagGroupId: string | null; description: string; colorToken: string };
export type FoundationAssignment = { id: string; contactId: string; tagId: string; sourceType: string; sourceId: string | null; removedAt: string | null };
export type FoundationField = { id: string; name: string; key: string; fieldType: string; options: string[]; isActive: boolean; sortOrder: number };
export type FoundationValue = { contactId: string; fieldId: string; value: unknown; sourceType: string };
export type FoundationSegment = { id: string; name: string; conditions: SegmentGroup; isActive: boolean; lastEstimatedCount: number | null };

type FoundationState = { groups: FoundationTagGroup[]; tags: FoundationTag[]; assignments: FoundationAssignment[]; fields: FoundationField[]; values: FoundationValue[]; segments: FoundationSegment[] };
const state: FoundationState = { groups: [], tags: [], assignments: [], fields: [], values: [], segments: [] };

export function foundationState(): FoundationState { return state; }
export function createTagGroup(input: { name: string; isExclusive?: boolean }): FoundationTagGroup { const item = { id: randomUUID(), name: input.name.trim(), isExclusive: Boolean(input.isExclusive), isActive: true }; state.groups.push(item); return item; }
export function createTag(input: unknown): FoundationTag { const parsed = tagDefinitionSchema.parse(input); const item: FoundationTag = { id: randomUUID(), ...parsed, tagGroupId: parsed.tagGroupId, isExclusive: parsed.isExclusive, isActive: true }; if (state.tags.some((tag) => tag.isActive && tag.name.toLowerCase() === item.name.toLowerCase())) throw new Error("同名の有効タグは作成できません。"); state.tags.push(item); return item; }
export function updateTag(id: string, input: Partial<FoundationTag>): FoundationTag { const item = state.tags.find((tag) => tag.id === id); if (!item) throw new Error("タグが見つかりません。"); Object.assign(item, input); return item; }
export function assignTag(input: { contactId: string; tagId: string; sourceType: string; sourceId?: string | null }): FoundationAssignment { const active = state.assignments.find((item) => item.contactId === input.contactId && item.tagId === input.tagId && item.sourceType === input.sourceType && item.sourceId === (input.sourceId ?? null) && !item.removedAt); if (active) return active; const tag = state.tags.find((item) => item.id === input.tagId); if (!tag) throw new Error("タグが見つかりません。"); if (tag.tagGroupId) { const group = state.groups.find((item) => item.id === tag.tagGroupId); if (group?.isExclusive) state.assignments.filter((item) => item.contactId === input.contactId && !item.removedAt && state.tags.find((candidate) => candidate.id === item.tagId)?.tagGroupId === tag.tagGroupId && item.sourceType !== "manual").forEach((item) => { item.removedAt = new Date().toISOString(); }); } const assignment = { id: randomUUID(), contactId: input.contactId, tagId: input.tagId, sourceType: input.sourceType, sourceId: input.sourceId ?? null, removedAt: null }; state.assignments.push(assignment); return assignment; }
export function removeTagAssignment(id: string): FoundationAssignment { const item = state.assignments.find((assignment) => assignment.id === id); if (!item) throw new Error("付与元が見つかりません。"); item.removedAt = new Date().toISOString(); return item; }
export function createField(input: unknown): FoundationField { const parsed = customFieldDefinitionSchema.parse(input); if (state.fields.some((field) => field.key === parsed.key)) throw new Error("同じkeyの項目は作成できません。"); const item = { id: randomUUID(), name: parsed.name, key: parsed.key, fieldType: parsed.fieldType, options: parsed.options, isActive: true, sortOrder: state.fields.length }; state.fields.push(item); return item; }
export function setFieldValue(input: { contactId: string; fieldId: string; value: unknown; sourceType?: string }): FoundationValue { const field = state.fields.find((item) => item.id === input.fieldId); if (!field) throw new Error("項目が見つかりません。"); const parsed = customFieldDefinitionSchema.shape.fieldType.parse(field.fieldType); if (parsed === "number" && (typeof input.value !== "number" || Number.isNaN(input.value))) throw new Error("number型の値が必要です。"); if (parsed === "boolean" && typeof input.value !== "boolean") throw new Error("boolean型の値が必要です。"); if (["single_select", "multi_select"].includes(parsed)) { const values = parsed === "multi_select" ? (Array.isArray(input.value) ? input.value : []) : [input.value]; if (values.some((value) => typeof value !== "string" || !field.options.includes(value))) throw new Error("定義済み選択肢だけを指定してください。"); } const existing = state.values.find((item) => item.contactId === input.contactId && item.fieldId === input.fieldId); if (existing) { existing.value = input.value; existing.sourceType = input.sourceType ?? "manual"; return existing; } const value = { contactId: input.contactId, fieldId: input.fieldId, value: input.value, sourceType: input.sourceType ?? "manual" }; state.values.push(value); return value; }
export function createSegment(input: { name: string; conditions: unknown }): FoundationSegment { const conditions = validateSegmentDsl(input.conditions); const item = { id: randomUUID(), name: input.name.trim(), conditions, isActive: true, lastEstimatedCount: null }; state.segments.push(item); return item; }
export function previewSegment(id: string, contacts: Array<{ id: string; friendStatus: string; followedAt: string | null; lastMessageAt: string | null }>): { count: number; sample: string[]; excluded: number } { const segment = state.segments.find((item) => item.id === id); if (!segment) throw new Error("セグメントが見つかりません。"); const eligible = contacts.filter((contact) => !isSuppressed(contact.friendStatus, "eligible")); const count = eligible.length; segment.lastEstimatedCount = count; return { count, sample: eligible.slice(0, 20).map((contact) => contact.id), excluded: contacts.length - eligible.length }; }
